@startuml
actor WHO as "WHO Advisor"

rectangle Database

rectangle "Information System"{
    usecase UC1 as "Produce country reports"

    usecase UC2 as "Produce city reports"

    usecase UC3 as "Produce region reports"

    WHO - UC1
    UC1 - UC2
    UC2 - UC3
    UC3 - Database

}
@enduml
